name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    if: github.repository == 'jazzband/django-celery-monitor'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group lint

      - name: Build package
        run: |
          uv run python -m build
          uv run twine check dist/*

      - name: Upload packages to Jazzband
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: jazzband
          password: ${{ secrets.JAZZBAND_RELEASE_KEY }}
          repository_url: https://jazzband.co/projects/django-celery-monitor/upload
